// <auto-generated />
using System;
using DataBaseServer.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DataBaseServer.Migrations
{
    [DbContext(typeof(BaseContext))]
    [Migration("20181105103329_addJob")]
    partial class addJob
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("DataBaseServer.DBO.FileInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("JobGuidFk");

                    b.Property<string>("Md5")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<DateTime>("Version");

                    b.Property<DateTime>("changed");

                    b.Property<long>("fileLength");

                    b.HasKey("Id");

                    b.HasIndex("JobGuidFk");

                    b.HasIndex("Md5")
                        .IsUnique();

                    b.ToTable("FileInfos");
                });

            modelBuilder.Entity("DataBaseServer.DBO.Job", b =>
                {
                    b.Property<string>("GUID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<DateTime>("changed");

                    b.Property<int>("status");

                    b.HasKey("GUID");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("DataBaseServer.DBO.FileInfo", b =>
                {
                    b.HasOne("DataBaseServer.DBO.Job", "Job")
                        .WithMany("fileInfos")
                        .HasForeignKey("JobGuidFk");
                });
#pragma warning restore 612, 618
        }
    }
}
