// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: database_service.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace GRPCService.DataBaseProto {
  public static partial class DataBase
  {
    static readonly string __ServiceName = "DataBaseProto.DataBase";

    static readonly grpc::Marshaller<global::GRPCService.DataBaseProto.PdfFileInfo> __Marshaller_DataBaseProto_PdfFileInfo = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GRPCService.DataBaseProto.PdfFileInfo.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::GRPCService.DataBaseProto.DatabaseCreateFileInfoResponse> __Marshaller_DataBaseProto_DatabaseCreateFileInfoResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GRPCService.DataBaseProto.DatabaseCreateFileInfoResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::GRPCService.DataBaseProto.PdfFileInfo, global::GRPCService.DataBaseProto.DatabaseCreateFileInfoResponse> __Method_SavePdfFileInfo = new grpc::Method<global::GRPCService.DataBaseProto.PdfFileInfo, global::GRPCService.DataBaseProto.DatabaseCreateFileInfoResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SavePdfFileInfo",
        __Marshaller_DataBaseProto_PdfFileInfo,
        __Marshaller_DataBaseProto_DatabaseCreateFileInfoResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::GRPCService.DataBaseProto.DatabaseServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of DataBase</summary>
    public abstract partial class DataBaseBase
    {
      public virtual global::System.Threading.Tasks.Task<global::GRPCService.DataBaseProto.DatabaseCreateFileInfoResponse> SavePdfFileInfo(global::GRPCService.DataBaseProto.PdfFileInfo request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for DataBase</summary>
    public partial class DataBaseClient : grpc::ClientBase<DataBaseClient>
    {
      /// <summary>Creates a new client for DataBase</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public DataBaseClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for DataBase that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public DataBaseClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected DataBaseClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected DataBaseClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::GRPCService.DataBaseProto.DatabaseCreateFileInfoResponse SavePdfFileInfo(global::GRPCService.DataBaseProto.PdfFileInfo request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SavePdfFileInfo(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::GRPCService.DataBaseProto.DatabaseCreateFileInfoResponse SavePdfFileInfo(global::GRPCService.DataBaseProto.PdfFileInfo request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SavePdfFileInfo, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::GRPCService.DataBaseProto.DatabaseCreateFileInfoResponse> SavePdfFileInfoAsync(global::GRPCService.DataBaseProto.PdfFileInfo request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SavePdfFileInfoAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::GRPCService.DataBaseProto.DatabaseCreateFileInfoResponse> SavePdfFileInfoAsync(global::GRPCService.DataBaseProto.PdfFileInfo request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SavePdfFileInfo, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override DataBaseClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new DataBaseClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(DataBaseBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SavePdfFileInfo, serviceImpl.SavePdfFileInfo).Build();
    }

  }
}
#endregion
